<a href="https://colab.research.google.com/github/Shanmugapriya2406/Multiple_disease_prediction/blob/main/liver_disease_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
liver_df=pd.read_csv('/content/indian_liver_patient - indian_liver_patient.csv')
liver_df.head()

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
0,65,Female,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,Male,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,Male,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,Male,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,Male,3.9,2.0,195,27,59,7.3,2.4,0.40,1

In [3]:
liver_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         583 non-null    int64
 1   Gender                      583 non-null    object
 2   Total_Bilirubin             583 non-null    float64
 3   Direct_Bilirubin            583 non-null    float64
 4   Alkaline_Phosphotase        583 non-null    int64
 5   Alamine_Aminotransferase    583 non-null    int64
 6   Aspartate_Aminotransferase  583 non-null    int64
 7   Total_Protiens              583 non-null    float64
 8   Albumin                     583 non-null    float64
 9   Albumin_and_Globulin_Ratio  579 non-null    float64
 10  Dataset                     583 non-null    int64
dtypes: float64(5), int64(5), object(1)
memory usage: 50.2+ KB

In [4]:
liver_df.isnull().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    4
Dataset                       0
dtype: int64

In [5]:
liver_df.fillna(method='ffill',inplace=True)

<ipython-input-5-555da8c484fb>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  liver_df.fillna(method='ffill',inplace=True)

In [6]:
liver_df.isnull().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    0
Dataset                       0
dtype: int64

In [8]:
liver_df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
578    False
579    False
580    False
581    False
582    False
Length: 583, dtype: bool

In [12]:
liver_df['Gender'].replace({'Male':1,'Female':0},inplace=True)

<ipython-input-12-2754b7964e7a>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  liver_df['Gender'].replace({'Male':1,'Female':0},inplace=True)
<ipython-input-12-2754b7964e7a>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  liver_df['Gender'].replace({'Male':1,'Female':0},inplace=True)

In [13]:
liver_df['Dataset'].replace({1:0,2:1},inplace=True)

<ipython-input-13-67fea80a97e9>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  liver_df['Dataset'].replace({1:0,2:1},inplace=True)

In [14]:
liver_df

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
0,65,0,0.7,0.1,187,16,18,6.8,3.3,0.90,0
1,62,1,10.9,5.5,699,64,100,7.5,3.2,0.74,0
2,62,1,7.3,4.1,490,60,68,7.0,3.3,0.89,0
3,58,1,1.0,0.4,182,14,20,6.8,3.4,1.00,0
4,72,1,3.9,2.0,195,27,59,7.3,2.4,0.40,0
...,...,...,...,...,...,...,...,...,...,...,...
578,60,1,0.5,0.1,500,20,34,5.9,1.6,0.37,1
579,40,1,0.6,0.1,98,35,31,6.0,3.2,1.10,0
580,52,1,0.8,0.2,245,48,49,6.4,3.2,1.00,0
581,31,1,1.3,0.5,184,29,32,6.8,3.4,1.00,0
582,38,1,1.0,0.3,216,21,24,7.3,4.4,1.50,1

In [15]:
liver_df.corr()

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
Age,1.000000,0.056560,0.011763,0.007529,0.080425,-0.086883,-0.019910,-0.187461,-0.265924,-0.216288,-0.137351
Gender,0.056560,1.000000,0.089291,0.100436,-0.027496,0.082332,0.080336,-0.089121,-0.093799,-0.003248,-0.082416
Total_Bilirubin,0.011763,0.089291,1.000000,0.874618,0.206669,0.214065,0.237831,-0.008099,-0.222250,-0.205984,-0.220208
Direct_Bilirubin,0.007529,0.100436,0.874618,1.000000,0.234939,0.233894,0.257544,-0.000139,-0.228531,-0.199834,-0.246046
Alkaline_Phosphotase,0.080425,-0.027496,0.206669,0.234939,1.000000,0.125680,0.167196,-0.028514,-0.165453,-0.233579,-0.184866
Alamine_Aminotransferase,-0.086883,0.082332,0.214065,0.233894,0.125680,1.000000,0.791966,-0.042518,-0.029742,-0.002441,-0.163416
Aspartate_Aminotransferase,-0.019910,0.080336,0.237831,0.257544,0.167196,0.791966,1.000000,-0.025645,-0.085290,-0.070019,-0.151934
Total_Protiens,-0.187461,-0.089121,-0.008099,-0.000139,-0.028514,-0.042518,-0.025645,1.000000,0.784053,0.231394,0.035008
Albumin,-0.265924,-0.093799,-0.222250,-0.228531,-0.165453,-0.029742,-0.085290,0.784053,1.000000,0.682836,0.161388
Albumin_and_Globulin_Ratio,-0.216288,-0.003248,-0.205984,-0.199834,-0.233579,-0.002441,-0.070019,0.231394,0.682836,1.000000,0.164606
Dataset,-0.137351,-0.082416,-0.220208,-0.246046,-0.184866,-0.163416,-0.151934,0.035008,0.161388,0.164606,1.000000

In [16]:
x=liver_df.drop('Dataset',axis=1)
y=liver_df['Dataset']

In [17]:
print(x)

     Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0     65       0              0.7               0.1                   187
1     62       1             10.9               5.5                   699
2     62       1              7.3               4.1                   490
3     58       1              1.0               0.4                   182
4     72       1              3.9               2.0                   195
..   ...     ...              ...               ...                   ...
578   60       1              0.5               0.1                   500
579   40       1              0.6               0.1                    98
580   52       1              0.8               0.2                   245
581   31       1              1.3               0.5                   184
582   38       1              1.0               0.3                   216

     Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8
1                          64                         100             7.5
2                          60                          68             7.0
3                          14                          20             6.8
4                          27                          59             7.3
..                        ...                         ...             ...
578                        20                          34             5.9
579                        35                          31             6.0
580                        48                          49             6.4
581                        29                          32             6.8
582                        21                          24             7.3

     Albumin  Albumin_and_Globulin_Ratio
0        3.3                        0.90
1        3.2                        0.74
2        3.3                        0.89
3        3.4                        1.00
4        2.4                        0.40
..       ...                         ...
578      1.6                        0.37
579      3.2                        1.10
580      3.2                        1.00
581      3.4                        1.00
582      4.4                        1.50

[583 rows x 10 columns]

In [18]:
print(y)

0      0
1      0
2      0
3      0
4      0
      ..
578    1
579    0
580    0
581    0
582    1
Name: Dataset, Length: 583, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((466, 10), (117, 10), (466,), (117,))

In [20]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier().fit(x_train,y_train)
y_pred=model.predict(x_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      0.86      0.81        85
           1       0.45      0.31      0.37        32

    accuracy                           0.71       117
   macro avg       0.61      0.59      0.59       117
weighted avg       0.68      0.71      0.69       117

In [21]:
from xgboost import XGBClassifier
model1=XGBClassifier().fit(x_train,y_train)
y_pred=model1.predict(x_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.78      0.75      0.77        85
           1       0.40      0.44      0.42        32

    accuracy                           0.67       117
   macro avg       0.59      0.60      0.59       117
weighted avg       0.68      0.67      0.67       117

In [22]:
input=(65,0,0.7,0.1,187,16,18,6.8,3.3,0.90)

In [23]:
input_as_numpy_array = np.asarray(input)

In [24]:
input_reshaped = input_as_numpy_array.reshape(1,-1)

In [25]:
ld_prediction = model.predict(input_reshaped)
print(ld_prediction)
if (ld_prediction[0] == 0):
  print("The Person does not have chronic kidney disease")

else:
  print("The Person has chronic kidney disease")

[0]
The Person does not have chronic kidney disease

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [26]:
import pickle

In [27]:
filename="liver_disease_prediction.txt"
pickle.dump(model,open(filename,'wb'))

In [29]:
loaded_model = pickle.load(open('liver_disease_prediction.txt', 'rb'))